name: MSF Updates Generation

on:
  schedule:
    - cron: '0 9 * * *'
  workflow_dispatch:

jobs:
  msf_emailgen:
    runs-on: ubuntu-latest

    steps:
      # Step: Checkout the repository
        - name: Checkout Repository
          uses: actions/checkout@v4

      # Step: Run inside Docker container
        - name: Generate updates
          run: |
            git clone https://github.com/rapid7/metasploit-framework.git metasploit-framework &&
            cd metasploit-framework &&
            yesterday=$(bash -c "date -d '1 day ago' '+%Y-%m-%d'") &&
            git log --stat -c --after=\"\$yesterday 00:00\" --before=\"\$yesterday 23:59\" > ../\${yesterday}_updates.txt &&
            cd .. &&
            cat ${yesterday}_updates.txt

        - name: Save updates.txt to Updates folder
          run: |
            mkdir -p updates &&
            mv ${yesterday}_updates.txt updates/
