name: MSF Updates Generation

on:
  schedule:
    - cron: '0 9 * * *'
  workflow_dispatch:


env:
  YESTERDAY: \"$(date -d "1 day ago" '+%Y-%m-%d')\"


jobs:
  msf_emailgen:
    permissions: 
      contents: write
    runs-on: ubuntu-latest

    steps:
      # Step: Checkout the repository
        - name: Checkout Repository
          uses: actions/checkout@v4

      # Step: Run inside Docker container
        - name: Generate updates
          run: |
            git clone https://github.com/rapid7/metasploit-framework.git metasploit-framework &&
            cd metasploit-framework &&
            ls -la &&
            yesterday=${{ env.YESTERDAY }} &&
            echo ${yesterday}
            git log --stat -c --after='${yesterday} 00:00' --before='${yesterday} 23:59' > ../${yesterday}_updates.txt &&
            cd .. &&
            ls -la &&
            cat ${yesterday}_updates.txt

        - name: Save updates.txt to Updates folder
          run: |
            mkdir -p updates &&
            yesterday=${{ env.YESTERDAY }} &&
            mv ${yesterday}_updates.txt updates/ &&
            ls -la updates

        - name: Commit & push changes
          uses: action-js/push@main
          with:
            github_token: ${{ secrets.PAT }}
