name: MSF Updates Generation

on:
  schedule:
    - cron: '0 9 * * *'
  workflow_dispatch:


env:
  YESTERDAY: \"$(date -d "3 day ago" '+%Y-%m-%d')\"


jobs:
  msf_emailgen:
    permissions: 
      contents: write
    runs-on: ubuntu-latest

    steps:
      # Step: Checkout the repository
        - name: Checkout Repository
          uses: actions/checkout@v4

      # Step: Run inside Docker container
        - name: Generate updates
          run: |
            git clone https://github.com/rapid7/metasploit-framework.git metasploit-framework &&
            cd metasploit-framework &&
            yesterday=${{ env.YESTERDAY }} &&
            echo ${yesterday}
            git log --stat -c --after='${yesterday} 00:00' --before='${yesterday} 23:59' > ../${yesterday}_updates.txt &&
            cd .. &&
            cat ${yesterday}_updates.txt

        - name: Save updates.txt to Updates folder
          run: |
            mkdir -p updates &&
            yesterday=${{ env.YESTERDAY }} &&
            mv ${yesterday}_updates.txt updates/ &&
            ls -la updates

        - name:  Commit & push changes
          run: |
            yesterday=${{ env.YESTERDAY }} &&
            git config --global user.name "github-actions[bot]" &&
            git config --global user.email "github-actions[bot]@users.noreply.github.com" &&
            git add updates/${yesterday}_updates.txt &&
            git commit -m "Add updates for ${yesterday}" &&
            git push https://x-access-token:${{ secrets.PAT }}@github.com/RameshKrishnanNaraKrish/delete_1.git
